### ISSUE TITLE
Incorrectly resolves package.json when using Yarn v4 with the nodeLinker set to pnpm

### ISSUE THREAD

**Issue by Cellule** [isaacs/package-json-from-dist#1]
From https://github.com/isaacs/rimraf/issues/317

Here's a trace in findPackageJson
<img width="2046" alt="image" src="https://github.com/user-attachments/assets/21637867-c5fe-4435-bb10-cca25b2d35c6">

Since yarn with pnpm nodeLinker uses a `.store` folder inside `node_modules` then `findPackageJson` incorrectly thinks it needs to get `.../node_modules/.store/package.json`

**Comment by isaacs** [comment]
What is the full path to the package in a yarn v4 installation? Ie, where _is_ the package.json file?

**Comment by isaacs** [comment]
Oh, wait, is it in the screenshot? I can't read that. By that I mean: _it does not contain text_, it's just brownish black noise with some blue lines on it.

Can you please put _the actual text_ from that screenshot into a code section in a comment?

Please do not post screenshots on github and expect people to be able to read them. Assume I'm literally blind.

Thank you.

**Comment by isaacs** [comment]
I'm assuming that this is fixed on v1.0.1. I was able to ORC the text out of the image, because macOS is less blind than I am.
